version: "3.8"
services:
  liferay71:
    image: liferay/dxp:7.1.10-sp6
    container_name: liferay71
    mem_limit: 3g
    ports:
      - "8080:8080"
      - "11311:11311"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./lr/liferay/files:/mnt/liferay/files
      - ./lr/liferay/scripts:/mnt/liferay/scripts
      - ./lr/liferay/deploy:/mnt/liferay/deploy
      - ./lr/liferay/files/data/document_library:/mnt/liferay/files/data/document_library
    environment:
      - bootstrap.memory_lock=true
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_PROJECT_ID=local
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=password
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://172.18.0.2/71eed?connectionCollation=utf8mb4_bin&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&characterEncoding=utf8
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED="false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
    networks:
      - lrnet
  liferay712:
    image: liferay/dxp:7.1.10-sp6
    container_name: liferay712
    mem_limit: 3g
    ports:
      - "8081:8080"
      - "11312:11312"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./lr2/liferay/files:/mnt/liferay/files
      - ./lr2/liferay/scripts:/mnt/liferay/scripts
      - ./lr2/liferay/deploy:/mnt/liferay/deploy
      - ./lr2/liferay/files/data/document_library:/mnt/liferay/files/data/document_library
    environment:
      - bootstrap.memory_lock=true
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_PROJECT_ID=local
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11312
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=password
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://172.18.0.2/71eed?connectionCollation=utf8mb4_bin&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&characterEncoding=utf8
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED="false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
    networks:
      - lrnet

networks:
  lrnet:
    name: mysql-compose_default
