version: "3.8"
services:
  elasticsearch654:
    container_name: elasticsearch654
    build: es
    mem_limit: 4g
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data/:/usr/share/elasticsearch/data/
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./es/logs/:/var/log/elasticsearch/
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      #- discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
    networks:
      - lrnet
  elasticsearch654_2:
    container_name: elasticsearch654_2
    build: es
    mem_limit: 4g
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es2/data/:/usr/share/elasticsearch/data/
      - ./es2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es2/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./es2/logs/:/var/log/elasticsearch/
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      #- discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
    networks:
      - lrnet
networks:
  lrnet:
    name: mysql-compose_default
